config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friends
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = current_user.friends.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def correct_user
      @friend = current_user.friends.find_by(id: params[:id])
      redirect_to friends_path, alert: "Not Authorized To Make Changes!" if @friend.nil?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index

  end

  def about
    @about_me = "Hi, I'm Sergey..."
    @answer = 2 + 2
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, class: "form-control" %>
  </div>

    <%= form.number_field :user_id, id: :friend_user_id, class: "form-control", value: current_user.id,type: "hidden" %>

  <br/>
  <div class="actions ">
    <%= form.submit class: 'btn btn-secondary', style: 'width: 100%' %>
  </div>
  
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>
<%= render 'form', friend: @friend %>

app/views/friends/index.html.erb
<table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= link_to friend.first_name+" "+friend.last_name, friend, class: "text-reset text-decoration-none", title: "Show Details" %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        <td><%= link_to '✎', edit_friend_path(friend), class: "text-reset text-decoration-none", title: "Edit" %></td>
        <td><%= link_to '❌', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-reset text-decoration-none", title: "Delete" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Friend', new_friend_path, class: 'btn btn-secondary'%>

app/views/friends/new.html.erb
<h1>New Friend</h1>
<%= render 'form', friend: @friend %>

app/views/friends/show.html.erb
<div class="h-100 p-5 bg-light border rounded-3 position-relative">
  <h2 class="position-absolute top-10 start-50 translate-middle"><%= @friend.first_name %> <%= @friend.last_name %></h2><br/>
  <p><strong>Email: </strong><%= @friend.email %></p>
  <p><strong>Phone: </strong><%= @friend.phone %></p>
  <p><strong>Twitter: </strong><%= @friend.twitter %></p><br/>
  <span class="position-absolute top-90 start-50 translate-middle ">
    <%= link_to 'Edit', edit_friend_path(@friend), class: 'btn btn-secondary' %>
    <%= link_to 'Back', friends_path, class: 'btn btn-dark' %>
  </span>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <%= link_to "Friends List", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"  data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"    aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <% if user_signed_in? %>
                    <li class="nav-item">
                        <%= link_to "Friends", friends_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "New Friend", new_friend_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link"   %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
                    </li>
                <% end %>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

app/views/home/about.html.erb
<h1>About Me...</h1>

<p>
	<%= @about_me %>
</p>

<p>
	
	2 + 2 = <%= @answer %>
</p>

app/views/home/index.html.erb
<%= image_tag 'wall.jpg', class: "img-fluid" %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <title>Friends List</title>
  </head>
  <body>
    <%= render "home/header" %>
    <div class="container mt-4">
      <% if notice.present? %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= notice %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <% if alert.present? %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= alert %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <%= yield %>
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    -->
  </body>
</html>